In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [3]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a*b

array([2., 4., 6., 8.])

In [6]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [7]:
a = np.arange(10000)
%timeit a + 1  

6.87 µs ± 411 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
l = range(10000)
%timeit [i+1 for i in l] 

553 µs ± 47.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
c = np.ones((3, 3))
c * c 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [12]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_and(a, b)

array([ True, False, False, False])

In [13]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
np.log(a)

D:\Anaconda3\envs\mentoring_rm_3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [15]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
a = np.triu(np.ones((3, 3)), 1)   # upper triangle 
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [17]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [19]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [20]:
x.sum(axis = 0)

array([3, 3])

In [21]:
x.sum(axis=1)

array([2, 4])

In [22]:
x[:, 0].sum(), x[:, 1].sum(), x[1,0].sum()

(3, 3, 2)

In [23]:
x = np.array([1, 3, 2])
x.max()

3

In [25]:
x.argmin()

0

In [26]:
np.all([True, True, False])

False

In [27]:
np.any([True, True, False])

True

In [28]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [29]:
np.median(x)

1.5

In [31]:
np.median(y, axis=-1)

array([2., 5.])

In [32]:
x.std()

0.82915619758885

In [33]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [35]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [40]:
a = np.ones((4, 5))
a[2,2:] = 10
a

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., 10., 10., 10.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [41]:
a = np.arange(0, 40, 10)
a.shape

(4,)

In [42]:
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape

(4, 1)

In [43]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [57]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [62]:
b = a.ravel()
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [65]:
z[np.newaxis, :]

array([[1, 2, 3]])

In [66]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [73]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [75]:
a[3, 2, 1 ]

23

In [76]:
b = a.transpose(1, 2, 0)
b.shape

(3, 2, 4)

In [77]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [78]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [79]:
a[j]

array([1, 2, 3, 4])

In [80]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)